web: gunicorn techtalk.wsgi --chdir backend --limit-request-line 8188 --log-file -
worker: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=techtalk worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery --workdir backend --app=techtalk beat -S redbeat.RedBeatScheduler --loglevel=info
